baseURL = "http://concon2015.github.io/"
languageCode = "en-us"
title = "Connor Blackard Online Resume"
theme= "hugo-resume"
publishDir = "docs"

[params]
    firstName = "Connor"
    lastName = "Blackard"
    address = "College Station, TX"
    phone = "817-719-5788"
    #contactNote = "Dev Tools Engineer" #used in QR code only
    profileImage = "img/me.png"
    email = "connorblackard@gmail.com"
    description = "Senior Technology Management Major at Texas A&M University."
    favicon = "images/favicon.ico"

    # what sections to display.  Setting to false disables navigation and section.
    showSkills = true
    showProjects = true
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true
    showQr = false

    # do you want to show git hash on page footer and link to repo? Add commit URl for repo here.
    #gitCommitPrefix = "https://github.com/YOURNAME/REPONAME/commit/"


[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/connorblackard/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/concon2015/"

#[[params.handles]]
#    name = "Bitbucket"
#    link = "https://bitbucket.org/eddiewebb/"

#[[params.handles]]
#    name = "Stack Overflow"
#    link = "https://stackoverflow.com/users/story/82880"
#    icon = "stack-overflow" #optional icon attribute used for Font Awesome icons, otherwise the name is lowercased.

#[[params.handles]]
#    name = "Keybase"
#    link = "https://keybase.io/edwardawebb"
#    icon = "key" #optional icon attribute used for Font Awesome icons, otherwise the name is lowercased.

#[params.google.analytics]
#    trackerID = "XX-123446-01"

#[outputs] #only required for search
#    home = ["HTML", "JSON"]
